UPDATE questionnaire_section SET question_json = '{ "questions": [ { "id": "26", "question": "Su Institución cuenta con un Comité de Educación.", "priority": 1 }, { "id": "27", "question": "Su Institución cuenta con un Comité de Administración y Finanzas.", "priority": 1 }, { "id": "28", "question": "Su Institución cuenta con un Comité de Procuración de Fondos.", "priority": 1 }, { "id": "29", "question": "Su Institución cuenta con un Comité de Estatus y Reglamentos.", "priority": 1 }, { "id": "30", "question": "Su Institución cuenta con un Comité para Proyectos Especiales.", "priority": 1 }, { "id": "31", "question": "Su Institución cuenta con un Comité de Auditoría y Vigilancia.", "priority": 1 } ] } ' WHERE id = 'ac1.3';
UPDATE questionnaire_section SET question_json = '{ "questions": [ { "id": "81", "question": "Tiene Aviso de Privacidad para sus donantes.", "priority": 1 }, { "id": "82", "question": "Tiene Aviso de Privacidad para sus empleados.", "priority": 1 }, { "id": "83", "question": "Tiene Aviso de Privacidad para su población beneficiada.", "priority": 1 } ] } ' WHERE id = 'ac2.4';
UPDATE questionnaire_section SET question_json = '{"dependsOn":"basic","questions":[{"id":"84.4.2","dependsOn":"84.4.1","question":"Cuenta con:","options":[{"name":"Clave de incorporación a la SEP","valueable":true},{"name":"Acreditación de alumnos por parte del INEA","valueable":true},{"name":"Ninguno","valueable":false}],"priority":4},{"id":"84.4.3","dependsOn":"84.4.1","question":"Las instalaciones de la escuela cumplen con los requisitos establecidos por la SEP para este nivel educativo.","priority":1}]}' WHERE id = 'ac2.5.4';
UPDATE questionnaire_section SET question_json = '{"dependsOn":"secondary","questions":[{"id":"84.5.2","dependsOn":"84.5.1","question":"Cuenta con:","options":[{"name":"Clave de incorporación a la SEP","valueable":true},{"name":"Acreditación de alumnos por parte del INEA","valueable":true},{"name":"Ninguno","valueable":false}],"priority":4},{"id":"84.5.3","dependsOn":"84.5.1","question":"Las instalaciones de la escuela cumplen con los requisitos establecidos para este nivel educativo.","priority":1}]}' WHERE id = 'ac2.5.5';

UPDATE questionnaire_section SET question_json = '{"questions":[{"id":"158","question":"Otorga Prima Vacacional.","priority":1},{"id":"159","question":"Otorga Aguinaldo.","priority":1},{"id":"160","question":"Cuenta con jornadas de trabajo detalladas para sus colaboradores.","priority":1},{"id":"161","question":"Ofrece días de descanso y días oficiales con goce de sueldo a sus colaboradores","priority":1},{"id":"162","question":"Ofrece un período anual de vacaciones con goce de sueldo a sus colaboradores. ","priority":1},{"id":"163","question":"Financia capacitaciones a sus colaboradores dentro de su horario laboral, con el objetivo que ellos adquieran nuevos conocimientos, habilidades o destrezas en su desempeño.","priority":1}]}' WHERE id = 'ac5.4';
UPDATE questionnaire_section SET question_json = '{ "questions": [ { "id": "14", "question": "El Consejo Directivo/Mesa Directiva presenta el informe anual de transparencia de la Institución.", "priority": 1 }, { "id": "15", "question": "El Consejo Directivo/Mesa Directiva nombra al Director General de la Institución.", "priority": 4 }, { "id": "16", "question": "El Consejo Directivo/Mesa Directiva define, monitorea y fortalece los programas y servicios de la Institución.", "priority": 1 }, { "id": "17", "question": "El Consejo Directivo/Mesa Directiva  asegura la integridad legal y ética de la Institución, ofreciendo rendición de cuentas a la sociedad y a los donantes.", "priority": 4 }, { "id": "18", "question": "El Consejo Directivo/Mesa Directiva promueve la planeación estratégica de la Institución.", "priority": 4 }, { "id": "19", "question": "El Consejo Directivo/Mesa Directiva ejecuta la planeación estratégica de la Institución (participa en las acciones de manera concreta).", "priority": 4 }, { "id": "20", "question": "El Consejo Directivo/Mesa Directiva  apoya al Director General y evalúa su desempeño en la Institución.", "priority": 4 }, { "id": "21", "question": "El Consejo Directivo/Mesa Directiva  maneja los recursos de la Institución en forma eficiente y efectiva.", "priority": 1 }, { "id": "22", "question": "El Consejo Directivo/Mesa Directiva  recluta a nuevos consejeros.", "priority": 4 }, { "id": "23", "question": "El Consejo Directivo/Mesa Directiva orienta  a nuevos consejeros.", "priority": 1 }, { "id": "24", "question": "El Consejo Directivo/Mesa Directiva  evalúa el desempeño de los consejeros.", "priority": 1 }, { "id": "25", "question": "El Consejo Directivo/Mesa Directiva  crea y supervisa a los Comités de Apoyo para garantizar la operación y gestión de la Institución.", "priority": 1 } ] }' WHERE id = 'ac1.2';

UPDATE questionnaire_section SET name = 'RED EDUCA' WHERE name = 'Red Educa';
UPDATE questionnaire_section SET dimension = 'Trabajo Colaborativo' WHERE dimension = 'Red Educa';
